version: "3.9"
services:
  foxy_docker:
    build:
      context: ..
      dockerfile: docker/foxy_dev.Dockerfile
      target: foxy_user_ws
      args:
        - WS_DIR=${WS_DIR}
        - USERNAME=${USERNAME_DOCKER}
        - userid=${userid}
        - groupid=${groupid}
        - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
        - ROS_LOCALHOST_ONLY=${ROS_LOCALHOST_ONLY}
    container_name: foxy_dev_container
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      # GPU access
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia
    image: foxy_dev_image:latest
    # Required for communicating over the network
    network_mode: "host"
    ipc: "host"
    pid: "host"
    # Required for accessing hardware
    privileged: true
    tty: true
    stdin_open: true
    volumes:
      - ../src:/home/${USERNAME_DOCKER}/${WS_DIR}/src
      - /tmp/.X11-unix:/tmp/.X11-unix:rw


